import type { Metadata } from "next";
import localFont from "next/font/local";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const alpino = localFont({
  src: [
    {
      path: "../public/fonts/Alpino-Black.woff",
      weight: "800",
      style: "normal",
    },
    {
      path: "../public/fonts/Alpino-Light.woff",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-alpino",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={alpino.variable}
      >
        {children}
      </body>
    </html>
  );
}
